### ISSUE TITLE
Character Scale 

### ISSUE THREAD

**Issue by Orangexx** [black-garden-studios/Hitbox-Studio-Pro#11]
if the character scale is not 1, the box is not fit.

**Comment by cschoenig** [comment]
The hitboxes are child objects with colliders attached. At edit time the Hitbox Editor assumes it is working with a character at scale (1, 1, 1). If you scale that character it will try to scale the hitboxes with it. When you scale your character, are the hitboxes not sized correctly? Or are they not aligned correctly? Can you post a screenshot of the issue?

**Comment by Orangexx** [comment]
Like this
The hitboxes are attached when games start, so don’t get the scale?

And sometime the hitboxes is not show in the editor, but the animation show event, and game running right. Maybe because I disable the HitboxManager during the editor and run time?



________________________________
发件人: Christian Schoenig III <notifications@github.com>
发送时间: Monday, March 4, 2019 3:08:14 PM
收件人: black-garden-studios/Hitbox-Studio-Pro
抄送: SuperAHao; Author
主题: Re: [black-garden-studios/Hitbox-Studio-Pro] Character Scale (#11)


The hitboxes are child objects with colliders attached. At edit time the Hitbox Editor assumes it is working with a character at scale (1, 1, 1). If you scale that character it will try to scale the hitboxes with it. When you scale your character, are the hitboxes not sized correctly? Or are they not aligned correctly? Can you post a screenshot of the issue?

―

**Comment by cschoenig** [comment]
In your gizmos menu make sure the Hitbox Manager gizmo is enabled, otherwise it will not render the hitboxes in your scene view. The hitboxes are attached on Awake(). I did some testing in one of my projects. For me the colliders themselves are scaled and aligned correctly however the preview that is being rendered by the hitbox manager is incorrect. I will add this issue to the next patch. Let me know if your problem is identical. The scene view should show you the collider outlines by selecting your character in the hierarchy at run time. 
![scaled](https://user-images.githubusercontent.com/10351268/53722589-ebb0d680-3e33-11e9-8058-c529d00fb9ac.PNG)

**Comment by cschoenig** [comment]
This should be fixed in 1.1.1
